// This file is generated by scripts/db/gen-types.mjs from supabase/migrations.
// Do not edit by hand: run `npm run db:types` after changing a migration.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "13"
  }
  public: {
    Tables: {
      activity_log: {
        Row: {
          id: number
          room_id: string
          actor_id: string | null
          action: string
          entity_type: string | null
          entity_id: string | null
          metadata: Json
          created_at: string
        }
        Insert: {
          id?: never
          room_id: string
          actor_id?: string | null
          action: string
          entity_type?: string | null
          entity_id?: string | null
          metadata?: Json
          created_at?: string
        }
        Update: {
          id?: never
          room_id?: string
          actor_id?: string | null
          action?: string
          entity_type?: string | null
          entity_id?: string | null
          metadata?: Json
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "activity_log_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "activity_log_room_id_fkey"
            columns: ["room_id"]
            isOneToOne: false
            referencedRelation: "rooms"
            referencedColumns: ["id"]
          },
        ]
      }
      application_requirements: {
        Row: {
          id: string
          application_id: string
          kind: Database["public"]["Enums"]["requirement_kind"]
          label: string
          is_done: boolean
          notes: string | null
          sort_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          application_id: string
          kind?: Database["public"]["Enums"]["requirement_kind"]
          label: string
          is_done?: boolean
          notes?: string | null
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          application_id?: string
          kind?: Database["public"]["Enums"]["requirement_kind"]
          label?: string
          is_done?: boolean
          notes?: string | null
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "application_requirements_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: false
            referencedRelation: "applications"
            referencedColumns: ["id"]
          },
        ]
      }
      applications: {
        Row: {
          id: string
          user_id: string
          country_code: string | null
          university_id: string | null
          program_id: string | null
          university_name: string
          program_name: string
          degree_level: Database["public"]["Enums"]["degree_level"] | null
          intake_term: Database["public"]["Enums"]["intake_term"] | null
          intake_year: number | null
          portal_url: string | null
          status: Database["public"]["Enums"]["application_status"]
          submitted_at: string | null
          application_fee_amount: number | null
          application_fee_currency: string | null
          tuition_amount: number | null
          tuition_currency: string | null
          tuition_period: Database["public"]["Enums"]["tuition_period"] | null
          funding_info: string | null
          result_date: string | null
          decision_notes: string | null
          notes: string | null
          visibility: Database["public"]["Enums"]["application_visibility"]
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id?: string
          country_code?: string | null
          university_id?: string | null
          program_id?: string | null
          university_name: string
          program_name?: string
          degree_level?: Database["public"]["Enums"]["degree_level"] | null
          intake_term?: Database["public"]["Enums"]["intake_term"] | null
          intake_year?: number | null
          portal_url?: string | null
          status?: Database["public"]["Enums"]["application_status"]
          submitted_at?: string | null
          application_fee_amount?: number | null
          application_fee_currency?: string | null
          tuition_amount?: number | null
          tuition_currency?: string | null
          tuition_period?: Database["public"]["Enums"]["tuition_period"] | null
          funding_info?: string | null
          result_date?: string | null
          decision_notes?: string | null
          notes?: string | null
          visibility?: Database["public"]["Enums"]["application_visibility"]
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          country_code?: string | null
          university_id?: string | null
          program_id?: string | null
          university_name?: string
          program_name?: string
          degree_level?: Database["public"]["Enums"]["degree_level"] | null
          intake_term?: Database["public"]["Enums"]["intake_term"] | null
          intake_year?: number | null
          portal_url?: string | null
          status?: Database["public"]["Enums"]["application_status"]
          submitted_at?: string | null
          application_fee_amount?: number | null
          application_fee_currency?: string | null
          tuition_amount?: number | null
          tuition_currency?: string | null
          tuition_period?: Database["public"]["Enums"]["tuition_period"] | null
          funding_info?: string | null
          result_date?: string | null
          decision_notes?: string | null
          notes?: string | null
          visibility?: Database["public"]["Enums"]["application_visibility"]
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "applications_country_code_fkey"
            columns: ["country_code"]
            isOneToOne: false
            referencedRelation: "countries"
            referencedColumns: ["code"]
          },
          {
            foreignKeyName: "applications_program_id_fkey"
            columns: ["program_id"]
            isOneToOne: false
            referencedRelation: "programs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "applications_university_id_fkey"
            columns: ["university_id"]
            isOneToOne: false
            referencedRelation: "universities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "applications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      attachments: {
        Row: {
          id: string
          room_id: string
          storage_path: string
          file_name: string
          mime_type: string
          size_bytes: number
          description: string
          uploaded_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          room_id: string
          storage_path: string
          file_name: string
          mime_type?: string
          size_bytes: number
          description?: string
          uploaded_by?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          room_id?: string
          storage_path?: string
          file_name?: string
          mime_type?: string
          size_bytes?: number
          description?: string
          uploaded_by?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "attachments_room_id_fkey"
            columns: ["room_id"]
            isOneToOne: false
            referencedRelation: "rooms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "attachments_uploaded_by_fkey"
            columns: ["uploaded_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      comments: {
        Row: {
          id: string
          room_id: string
          application_id: string | null
          note_id: string | null
          target_id: string | null
          attachment_id: string | null
          parent_id: string | null
          body: string
          author_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          room_id: string
          application_id?: string | null
          note_id?: string | null
          target_id?: string | null
          attachment_id?: string | null
          parent_id?: string | null
          body: string
          author_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          room_id?: string
          application_id?: string | null
          note_id?: string | null
          target_id?: string | null
          attachment_id?: string | null
          parent_id?: string | null
          body?: string
          author_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "comments_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: false
            referencedRelation: "applications"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "comments_attachment_id_fkey"
            columns: ["attachment_id"]
            isOneToOne: false
            referencedRelation: "attachments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "comments_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "comments_note_id_fkey"
            columns: ["note_id"]
            isOneToOne: false
            referencedRelation: "notes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "comments_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "comments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "comments_room_id_fkey"
            columns: ["room_id"]
            isOneToOne: false
            referencedRelation: "rooms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "comments_target_id_fkey"
            columns: ["target_id"]
            isOneToOne: false
            referencedRelation: "room_targets"
            referencedColumns: ["id"]
          },
        ]
      }
      countries: {
        Row: {
          code: string
          name_en: string
          name_fa: string
          flag_emoji: string | null
          region: string
          currency_code: string | null
          is_published: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          code: string
          name_en: string
          name_fa: string
          flag_emoji?: string | null
          region?: string
          currency_code?: string | null
          is_published?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          code?: string
          name_en?: string
          name_fa?: string
          flag_emoji?: string | null
          region?: string
          currency_code?: string | null
          is_published?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      country_guides: {
        Row: {
          id: string
          country_code: string
          locale: string
          section: Database["public"]["Enums"]["guide_section"]
          body_md: string
          source_url: string | null
          last_verified_at: string | null
          is_placeholder: boolean
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          country_code: string
          locale: string
          section: Database["public"]["Enums"]["guide_section"]
          body_md?: string
          source_url?: string | null
          last_verified_at?: string | null
          is_placeholder?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          country_code?: string
          locale?: string
          section?: Database["public"]["Enums"]["guide_section"]
          body_md?: string
          source_url?: string | null
          last_verified_at?: string | null
          is_placeholder?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "country_guides_country_code_fkey"
            columns: ["country_code"]
            isOneToOne: false
            referencedRelation: "countries"
            referencedColumns: ["code"]
          },
          {
            foreignKeyName: "country_guides_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      country_links: {
        Row: {
          id: string
          country_code: string
          label_en: string
          label_fa: string | null
          url: string
          category: string
          description: string
          last_verified_at: string | null
          is_placeholder: boolean
          sort_order: number
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          country_code: string
          label_en: string
          label_fa?: string | null
          url: string
          category?: string
          description?: string
          last_verified_at?: string | null
          is_placeholder?: boolean
          sort_order?: number
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          country_code?: string
          label_en?: string
          label_fa?: string | null
          url?: string
          category?: string
          description?: string
          last_verified_at?: string | null
          is_placeholder?: boolean
          sort_order?: number
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "country_links_country_code_fkey"
            columns: ["country_code"]
            isOneToOne: false
            referencedRelation: "countries"
            referencedColumns: ["code"]
          },
          {
            foreignKeyName: "country_links_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      deadlines: {
        Row: {
          id: string
          application_id: string
          label: string
          due_at: string
          is_done: boolean
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          application_id: string
          label?: string
          due_at: string
          is_done?: boolean
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          application_id?: string
          label?: string
          due_at?: string
          is_done?: boolean
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "deadlines_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: false
            referencedRelation: "applications"
            referencedColumns: ["id"]
          },
        ]
      }
      edit_proposals: {
        Row: {
          id: string
          entity_type: Database["public"]["Enums"]["kb_entity"]
          entity_id: string | null
          action: Database["public"]["Enums"]["proposal_action"]
          payload: Json
          base_snapshot: Json | null
          message: string
          status: Database["public"]["Enums"]["proposal_status"]
          proposed_by: string
          reviewed_by: string | null
          reviewed_at: string | null
          review_note: string | null
          result_entity_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          entity_type: Database["public"]["Enums"]["kb_entity"]
          entity_id?: string | null
          action: Database["public"]["Enums"]["proposal_action"]
          payload?: Json
          base_snapshot?: Json | null
          message?: string
          status?: Database["public"]["Enums"]["proposal_status"]
          proposed_by?: string
          reviewed_by?: string | null
          reviewed_at?: string | null
          review_note?: string | null
          result_entity_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          entity_type?: Database["public"]["Enums"]["kb_entity"]
          entity_id?: string | null
          action?: Database["public"]["Enums"]["proposal_action"]
          payload?: Json
          base_snapshot?: Json | null
          message?: string
          status?: Database["public"]["Enums"]["proposal_status"]
          proposed_by?: string
          reviewed_by?: string | null
          reviewed_at?: string | null
          review_note?: string | null
          result_entity_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "edit_proposals_proposed_by_fkey"
            columns: ["proposed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "edit_proposals_reviewed_by_fkey"
            columns: ["reviewed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      kb_revisions: {
        Row: {
          id: number
          entity_type: Database["public"]["Enums"]["kb_entity"]
          entity_id: string
          action: string
          old_data: Json | null
          new_data: Json | null
          proposal_id: string | null
          changed_by: string | null
          changed_at: string
        }
        Insert: {
          id?: never
          entity_type: Database["public"]["Enums"]["kb_entity"]
          entity_id: string
          action: string
          old_data?: Json | null
          new_data?: Json | null
          proposal_id?: string | null
          changed_by?: string | null
          changed_at?: string
        }
        Update: {
          id?: never
          entity_type?: Database["public"]["Enums"]["kb_entity"]
          entity_id?: string
          action?: string
          old_data?: Json | null
          new_data?: Json | null
          proposal_id?: string | null
          changed_by?: string | null
          changed_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "kb_revisions_changed_by_fkey"
            columns: ["changed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "kb_revisions_proposal_id_fkey"
            columns: ["proposal_id"]
            isOneToOne: false
            referencedRelation: "edit_proposals"
            referencedColumns: ["id"]
          },
        ]
      }
      notes: {
        Row: {
          id: string
          room_id: string
          kind: Database["public"]["Enums"]["note_kind"]
          title: string
          body_md: string
          url: string | null
          is_pinned: boolean
          created_by: string | null
          updated_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          room_id: string
          kind?: Database["public"]["Enums"]["note_kind"]
          title: string
          body_md?: string
          url?: string | null
          is_pinned?: boolean
          created_by?: string | null
          updated_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          room_id?: string
          kind?: Database["public"]["Enums"]["note_kind"]
          title?: string
          body_md?: string
          url?: string | null
          is_pinned?: boolean
          created_by?: string | null
          updated_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "notes_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notes_room_id_fkey"
            columns: ["room_id"]
            isOneToOne: false
            referencedRelation: "rooms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notes_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          id: string
          display_name: string
          avatar_url: string | null
          field_of_study: string | null
          target_degree: Database["public"]["Enums"]["degree_level"] | null
          target_intake_term: Database["public"]["Enums"]["intake_term"] | null
          target_intake_year: number | null
          target_countries: string[]
          role: Database["public"]["Enums"]["user_role"]
          onboarded_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          display_name?: string
          avatar_url?: string | null
          field_of_study?: string | null
          target_degree?: Database["public"]["Enums"]["degree_level"] | null
          target_intake_term?: Database["public"]["Enums"]["intake_term"] | null
          target_intake_year?: number | null
          target_countries?: string[]
          role?: Database["public"]["Enums"]["user_role"]
          onboarded_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          display_name?: string
          avatar_url?: string | null
          field_of_study?: string | null
          target_degree?: Database["public"]["Enums"]["degree_level"] | null
          target_intake_term?: Database["public"]["Enums"]["intake_term"] | null
          target_intake_year?: number | null
          target_countries?: string[]
          role?: Database["public"]["Enums"]["user_role"]
          onboarded_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      program_deadlines: {
        Row: {
          id: string
          program_id: string
          intake_term: Database["public"]["Enums"]["intake_term"] | null
          intake_year: number | null
          round_label: string
          applicant_group: Database["public"]["Enums"]["applicant_group"]
          opens_at: string | null
          deadline_at: string
          notes: string
          source_url: string | null
          last_verified_at: string | null
          is_placeholder: boolean
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          program_id: string
          intake_term?: Database["public"]["Enums"]["intake_term"] | null
          intake_year?: number | null
          round_label?: string
          applicant_group?: Database["public"]["Enums"]["applicant_group"]
          opens_at?: string | null
          deadline_at: string
          notes?: string
          source_url?: string | null
          last_verified_at?: string | null
          is_placeholder?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          program_id?: string
          intake_term?: Database["public"]["Enums"]["intake_term"] | null
          intake_year?: number | null
          round_label?: string
          applicant_group?: Database["public"]["Enums"]["applicant_group"]
          opens_at?: string | null
          deadline_at?: string
          notes?: string
          source_url?: string | null
          last_verified_at?: string | null
          is_placeholder?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "program_deadlines_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "program_deadlines_program_id_fkey"
            columns: ["program_id"]
            isOneToOne: false
            referencedRelation: "programs"
            referencedColumns: ["id"]
          },
        ]
      }
      program_requirements: {
        Row: {
          id: string
          program_id: string
          kind: Database["public"]["Enums"]["requirement_kind"]
          description: string
          is_mandatory: boolean
          source_url: string | null
          last_verified_at: string | null
          is_placeholder: boolean
          sort_order: number
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          program_id: string
          kind?: Database["public"]["Enums"]["requirement_kind"]
          description: string
          is_mandatory?: boolean
          source_url?: string | null
          last_verified_at?: string | null
          is_placeholder?: boolean
          sort_order?: number
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          program_id?: string
          kind?: Database["public"]["Enums"]["requirement_kind"]
          description?: string
          is_mandatory?: boolean
          source_url?: string | null
          last_verified_at?: string | null
          is_placeholder?: boolean
          sort_order?: number
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "program_requirements_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "program_requirements_program_id_fkey"
            columns: ["program_id"]
            isOneToOne: false
            referencedRelation: "programs"
            referencedColumns: ["id"]
          },
        ]
      }
      programs: {
        Row: {
          id: string
          university_id: string
          name_en: string
          name_fa: string | null
          degree_level: Database["public"]["Enums"]["degree_level"]
          field: string
          languages: string[]
          duration_months: number | null
          tuition_amount_min: number | null
          tuition_amount_max: number | null
          tuition_currency: string | null
          tuition_period: Database["public"]["Enums"]["tuition_period"] | null
          application_fee_amount: number | null
          application_fee_currency: string | null
          website_url: string | null
          description_md: string
          source_url: string | null
          last_verified_at: string | null
          is_placeholder: boolean
          is_published: boolean
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          university_id: string
          name_en: string
          name_fa?: string | null
          degree_level: Database["public"]["Enums"]["degree_level"]
          field?: string
          languages?: string[]
          duration_months?: number | null
          tuition_amount_min?: number | null
          tuition_amount_max?: number | null
          tuition_currency?: string | null
          tuition_period?: Database["public"]["Enums"]["tuition_period"] | null
          application_fee_amount?: number | null
          application_fee_currency?: string | null
          website_url?: string | null
          description_md?: string
          source_url?: string | null
          last_verified_at?: string | null
          is_placeholder?: boolean
          is_published?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          university_id?: string
          name_en?: string
          name_fa?: string | null
          degree_level?: Database["public"]["Enums"]["degree_level"]
          field?: string
          languages?: string[]
          duration_months?: number | null
          tuition_amount_min?: number | null
          tuition_amount_max?: number | null
          tuition_currency?: string | null
          tuition_period?: Database["public"]["Enums"]["tuition_period"] | null
          application_fee_amount?: number | null
          application_fee_currency?: string | null
          website_url?: string | null
          description_md?: string
          source_url?: string | null
          last_verified_at?: string | null
          is_placeholder?: boolean
          is_published?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "programs_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "programs_university_id_fkey"
            columns: ["university_id"]
            isOneToOne: false
            referencedRelation: "universities"
            referencedColumns: ["id"]
          },
        ]
      }
      room_invites: {
        Row: {
          id: string
          room_id: string
          code: string
          role: Database["public"]["Enums"]["room_role"]
          created_by: string | null
          expires_at: string | null
          max_uses: number | null
          use_count: number
          revoked_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          room_id: string
          code?: string
          role?: Database["public"]["Enums"]["room_role"]
          created_by?: string | null
          expires_at?: string | null
          max_uses?: number | null
          use_count?: number
          revoked_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          room_id?: string
          code?: string
          role?: Database["public"]["Enums"]["room_role"]
          created_by?: string | null
          expires_at?: string | null
          max_uses?: number | null
          use_count?: number
          revoked_at?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "room_invites_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "room_invites_room_id_fkey"
            columns: ["room_id"]
            isOneToOne: false
            referencedRelation: "rooms"
            referencedColumns: ["id"]
          },
        ]
      }
      room_members: {
        Row: {
          room_id: string
          user_id: string
          role: Database["public"]["Enums"]["room_role"]
          joined_at: string
        }
        Insert: {
          room_id: string
          user_id: string
          role?: Database["public"]["Enums"]["room_role"]
          joined_at?: string
        }
        Update: {
          room_id?: string
          user_id?: string
          role?: Database["public"]["Enums"]["room_role"]
          joined_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "room_members_room_id_fkey"
            columns: ["room_id"]
            isOneToOne: false
            referencedRelation: "rooms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "room_members_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      room_shared_applications: {
        Row: {
          room_id: string
          application_id: string
          shared_by: string
          shared_at: string
        }
        Insert: {
          room_id: string
          application_id: string
          shared_by?: string
          shared_at?: string
        }
        Update: {
          room_id?: string
          application_id?: string
          shared_by?: string
          shared_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "room_shared_applications_application_id_fkey"
            columns: ["application_id"]
            isOneToOne: false
            referencedRelation: "applications"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "room_shared_applications_room_id_fkey"
            columns: ["room_id"]
            isOneToOne: false
            referencedRelation: "rooms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "room_shared_applications_shared_by_fkey"
            columns: ["shared_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      room_target_votes: {
        Row: {
          target_id: string
          room_id: string
          user_id: string
          interest: Database["public"]["Enums"]["target_interest"]
          created_at: string
          updated_at: string
        }
        Insert: {
          target_id: string
          room_id: string
          user_id?: string
          interest: Database["public"]["Enums"]["target_interest"]
          created_at?: string
          updated_at?: string
        }
        Update: {
          target_id?: string
          room_id?: string
          user_id?: string
          interest?: Database["public"]["Enums"]["target_interest"]
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "room_target_votes_room_id_fkey"
            columns: ["room_id"]
            isOneToOne: false
            referencedRelation: "rooms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "room_target_votes_target_id_fkey"
            columns: ["target_id"]
            isOneToOne: false
            referencedRelation: "room_targets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "room_target_votes_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      room_targets: {
        Row: {
          id: string
          room_id: string
          university_id: string | null
          program_id: string | null
          title: string
          country_code: string | null
          url: string | null
          notes: string
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          room_id: string
          university_id?: string | null
          program_id?: string | null
          title: string
          country_code?: string | null
          url?: string | null
          notes?: string
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          room_id?: string
          university_id?: string | null
          program_id?: string | null
          title?: string
          country_code?: string | null
          url?: string | null
          notes?: string
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "room_targets_country_code_fkey"
            columns: ["country_code"]
            isOneToOne: false
            referencedRelation: "countries"
            referencedColumns: ["code"]
          },
          {
            foreignKeyName: "room_targets_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "room_targets_program_id_fkey"
            columns: ["program_id"]
            isOneToOne: false
            referencedRelation: "programs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "room_targets_room_id_fkey"
            columns: ["room_id"]
            isOneToOne: false
            referencedRelation: "rooms"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "room_targets_university_id_fkey"
            columns: ["university_id"]
            isOneToOne: false
            referencedRelation: "universities"
            referencedColumns: ["id"]
          },
        ]
      }
      rooms: {
        Row: {
          id: string
          name: string
          description: string
          country_code: string | null
          intake_term: Database["public"]["Enums"]["intake_term"] | null
          intake_year: number | null
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string
          country_code?: string | null
          intake_term?: Database["public"]["Enums"]["intake_term"] | null
          intake_year?: number | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string
          country_code?: string | null
          intake_term?: Database["public"]["Enums"]["intake_term"] | null
          intake_year?: number | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "rooms_country_code_fkey"
            columns: ["country_code"]
            isOneToOne: false
            referencedRelation: "countries"
            referencedColumns: ["code"]
          },
          {
            foreignKeyName: "rooms_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      universities: {
        Row: {
          id: string
          country_code: string
          name_en: string
          name_fa: string | null
          city: string | null
          website_url: string | null
          institution_type: string | null
          description_md: string
          source_url: string | null
          last_verified_at: string | null
          is_placeholder: boolean
          is_published: boolean
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          country_code: string
          name_en: string
          name_fa?: string | null
          city?: string | null
          website_url?: string | null
          institution_type?: string | null
          description_md?: string
          source_url?: string | null
          last_verified_at?: string | null
          is_placeholder?: boolean
          is_published?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          country_code?: string
          name_en?: string
          name_fa?: string | null
          city?: string | null
          website_url?: string | null
          institution_type?: string | null
          description_md?: string
          source_url?: string | null
          last_verified_at?: string | null
          is_placeholder?: boolean
          is_published?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "universities_country_code_fkey"
            columns: ["country_code"]
            isOneToOne: false
            referencedRelation: "countries"
            referencedColumns: ["code"]
          },
          {
            foreignKeyName: "universities_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      university_directory: {
        Row: {
          id: string | null
          country_code: string | null
          name_en: string | null
          name_fa: string | null
          city: string | null
          website_url: string | null
          institution_type: string | null
          source_url: string | null
          last_verified_at: string | null
          is_placeholder: boolean | null
          updated_at: string | null
          program_count: number | null
          fields: string[] | null
          languages: string[] | null
          degree_levels: Database["public"]["Enums"]["degree_level"][] | null
          min_yearly_tuition: number | null
          max_yearly_tuition: number | null
          tuition_currency: string | null
          search_text: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      add_to_tracker: {
        Args: { p_program_id?: string; p_university_id?: string; p_locale?: string }
        Returns: string
      }
      approve_edit_proposal: {
        Args: { p_proposal_id: string; p_review_note?: string }
        Returns: string
      }
      create_room: {
        Args: { p_name: string; p_description?: string; p_country_code?: string; p_intake_term?: Database["public"]["Enums"]["intake_term"]; p_intake_year?: number }
        Returns: string
      }
      get_invite_preview: {
        Args: { p_code: string }
        Returns: {
            room_id: string | null
            room_name: string | null
            room_description: string | null
            role: Database["public"]["Enums"]["room_role"] | null
            expires_at: string | null
            member_count: number | null
            is_member: boolean | null
            is_valid: boolean | null
          }[]
      }
      get_profile_cards: {
        Args: { p_ids: string[] }
        Returns: {
            id: string | null
            display_name: string | null
            avatar_url: string | null
          }[]
      }
      get_room_applications: {
        Args: { p_room_id: string }
        Returns: {
            application_id: string | null
            owner_id: string | null
            owner_name: string | null
            owner_avatar_url: string | null
            country_code: string | null
            university_id: string | null
            university_name: string | null
            program_id: string | null
            program_name: string | null
            degree_level: Database["public"]["Enums"]["degree_level"] | null
            intake_term: Database["public"]["Enums"]["intake_term"] | null
            intake_year: number | null
            status: Database["public"]["Enums"]["application_status"] | null
            submitted_at: string | null
            result_date: string | null
            decision_notes: string | null
            portal_url: string | null
            application_fee_amount: number | null
            application_fee_currency: string | null
            tuition_amount: number | null
            tuition_currency: string | null
            tuition_period: Database["public"]["Enums"]["tuition_period"] | null
            funding_info: string | null
            shared_at: string | null
            updated_at: string | null
            next_deadline_at: string | null
            next_deadline_label: string | null
            requirements_done: number | null
            requirements_total: number | null
            comment_count: number | null
          }[]
      }
      get_shared_application: {
        Args: { p_room_id: string; p_application_id: string }
        Returns: Json
      }
      join_room: {
        Args: { p_code: string }
        Returns: string
      }
      list_my_rooms: {
        Args: never
        Returns: {
            id: string | null
            name: string | null
            description: string | null
            country_code: string | null
            intake_term: Database["public"]["Enums"]["intake_term"] | null
            intake_year: number | null
            created_at: string | null
            updated_at: string | null
            my_role: Database["public"]["Enums"]["room_role"] | null
            member_count: number | null
            shared_count: number | null
            target_count: number | null
            last_activity_at: string | null
          }[]
      }
      regenerate_room_invite: {
        Args: { p_room_id: string; p_role?: Database["public"]["Enums"]["room_role"]; p_expires_at?: string; p_max_uses?: number }
        Returns: {
            id: string
            room_id: string
            code: string
            role: Database["public"]["Enums"]["room_role"]
            created_by: string | null
            expires_at: string | null
            max_uses: number | null
            use_count: number
            revoked_at: string | null
            created_at: string
          }
      }
      reject_edit_proposal: {
        Args: { p_proposal_id: string; p_review_note?: string }
        Returns: undefined
      }
      set_application_sharing: {
        Args: { p_application_id: string; p_room_ids: string[] }
        Returns: undefined
      }
      set_target_interest: {
        Args: { p_target_id: string; p_interest?: Database["public"]["Enums"]["target_interest"] }
        Returns: undefined
      }
      set_user_role: {
        Args: { p_user_id: string; p_role: Database["public"]["Enums"]["user_role"] }
        Returns: undefined
      }
    }
    Enums: {
      applicant_group:
        | "all"
        | "domestic"
        | "eu_eea"
        | "international"
      application_status:
        | "researching"
        | "planning"
        | "preparing"
        | "submitted"
        | "interview"
        | "admitted"
        | "rejected"
        | "waitlisted"
        | "withdrawn"
      application_visibility:
        | "private"
        | "shared"
      degree_level:
        | "bachelor"
        | "master"
        | "phd"
        | "other"
      guide_section:
        | "overview"
        | "application_process"
        | "timeline"
        | "required_documents"
        | "language_requirements"
        | "tuition_scholarships"
        | "visa_process"
        | "cost_of_living"
      intake_term:
        | "fall"
        | "winter"
        | "spring"
        | "summer"
      kb_entity:
        | "country_guide"
        | "country_link"
        | "university"
        | "program"
        | "program_requirement"
        | "program_deadline"
      note_kind:
        | "note"
        | "link"
      proposal_action:
        | "create"
        | "update"
        | "delete"
      proposal_status:
        | "pending"
        | "approved"
        | "rejected"
        | "withdrawn"
      requirement_kind:
        | "language_test"
        | "gpa"
        | "cv"
        | "sop"
        | "lor"
        | "portfolio"
        | "gre"
        | "gmat"
        | "pre_evaluation"
        | "transcript"
        | "degree_certificate"
        | "passport"
        | "research_proposal"
        | "writing_sample"
        | "interview"
        | "application_form"
        | "fee_payment"
        | "other"
      room_role:
        | "owner"
        | "editor"
        | "viewer"
      target_interest:
        | "interested"
        | "applying"
        | "not_interested"
      tuition_period:
        | "year"
        | "semester"
        | "total"
      user_role:
        | "user"
        | "admin"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">
type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  T extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"]),
> = (DefaultSchema["Tables"] & DefaultSchema["Views"])[T] extends { Row: infer R } ? R : never

export type TablesInsert<T extends keyof DefaultSchema["Tables"]> =
  DefaultSchema["Tables"][T] extends { Insert: infer I } ? I : never

export type TablesUpdate<T extends keyof DefaultSchema["Tables"]> =
  DefaultSchema["Tables"][T] extends { Update: infer U } ? U : never

export type Enums<T extends keyof DefaultSchema["Enums"]> = DefaultSchema["Enums"][T]

export type FunctionReturns<T extends keyof DefaultSchema["Functions"]> =
  DefaultSchema["Functions"][T] extends { Returns: infer R } ? R : never

export const Constants = {
  public: {
    Enums: {
      applicant_group: ["all", "domestic", "eu_eea", "international"],
      application_status: ["researching", "planning", "preparing", "submitted", "interview", "admitted", "rejected", "waitlisted", "withdrawn"],
      application_visibility: ["private", "shared"],
      degree_level: ["bachelor", "master", "phd", "other"],
      guide_section: ["overview", "application_process", "timeline", "required_documents", "language_requirements", "tuition_scholarships", "visa_process", "cost_of_living"],
      intake_term: ["fall", "winter", "spring", "summer"],
      kb_entity: ["country_guide", "country_link", "university", "program", "program_requirement", "program_deadline"],
      note_kind: ["note", "link"],
      proposal_action: ["create", "update", "delete"],
      proposal_status: ["pending", "approved", "rejected", "withdrawn"],
      requirement_kind: ["language_test", "gpa", "cv", "sop", "lor", "portfolio", "gre", "gmat", "pre_evaluation", "transcript", "degree_certificate", "passport", "research_proposal", "writing_sample", "interview", "application_form", "fee_payment", "other"],
      room_role: ["owner", "editor", "viewer"],
      target_interest: ["interested", "applying", "not_interested"],
      tuition_period: ["year", "semester", "total"],
      user_role: ["user", "admin"],
    },
  },
} as const
